# Generated by Django 5.2.12 on 2026-03-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('manage_payments', 'Может изменять платежи')], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
