# Generated by Django 5.2.12 on 2026-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_orders_orde_created_f0ce29_idx_and_more'),
        ('payment', '0003_payment_amount_gt_0_payment_status_in_status_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'permissions': [('manage_payments', 'Может изменять платежи')], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payment_pay_created_671024_idx'),
        ),
    ]
