# Generated by Django 5.2.12 on 2026-04-28 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_reviews_rev_created_bdcc91_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Рейтинг не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Рейтинг не может быть больше 5')], verbose_name='Рейтинг'),
        ),
    ]
