# Generated by Django 5.2.12 on 2026-03-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'permissions': [('manage_coupons', 'Может изменять купоны')], 'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
    ]
