# Generated by Django 5.2.12 on 2026-03-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Купон'),
        ),
    ]
