# Generated by Django 5.2.12 on 2026-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-valid_from'], 'permissions': [('manage_coupons', 'Может изменять купоны')], 'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='coupons_cou_is_acti_a50634_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from'], name='coupons_cou_valid_f_0c1ca5_idx'),
        ),
    ]
