# Generated by Django 5.2.12 on 2026-03-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('manage_profiles', 'Может изменять профили')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
