# Generated by Django 5.2.12 on 2026-04-20 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='', max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=40, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
