# Generated by Django 5.2.12 on 2026-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yookassa_id',
            field=models.CharField(default=1, max_length=255, verbose_name='ID Платежа YooKassa'),
            preserve_default=False,
        ),
    ]
