# Generated by Django 5.2.12 on 2026-03-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_discount_order_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('manage_orders', 'Может изменять заказы')], 'verbose_name_plural': 'Заказы'},
        ),
    ]
