# Generated by Django 5.2.12 on 2026-04-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_orders_orde_created_f0ce29_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='yookassa_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID Платежа YooKassa'),
        ),
    ]
