# Generated by Django 5.2.12 on 2026-03-20 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon', verbose_name='Купон'),
        ),
    ]
