# Generated by Django 5.2.12 on 2026-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_coupon'),
        ('products', '0006_remove_product_price_gte_0_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_gt_0'),
        ),
    ]
