# Generated by Django 5.2.12 on 2026-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_quantity_gt_0'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_user_id_b645f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_session_5e1af5_idx',
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Ключ сессии'),
        ),
    ]
