# Generated by Django 5.2.12 on 2026-04-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_cart_cart_user_id_b645f9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_cart_id_4fb076_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_product_985dba_idx',
        ),
    ]
