# Generated by Django 5.2.12 on 2026-03-07 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'), models.Index(fields=['created_at'], name='products_ca_created_c2504d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
                ('image', models.ImageField(blank=True, default='img/products/hero-bg.jpg', null=True, upload_to='img/products/', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('sell_counter', models.PositiveIntegerField(verbose_name='Количество продаж')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Продукты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'), models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'), models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_gte_0'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quantity_gte_0'), models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='reserved_quantity_gte_0')],
            },
        ),
    ]
