# Generated by Django 5.2.12 on 2026-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', models.F('reserved_quantity'))), name='product_reserved_quantity_lte_quantity'),
        ),
    ]
