# Generated by Django 5.2.12 on 2026-03-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_reserved_quantity_lte_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'permissions': [('manage_categories', 'Может изменять категории')], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'permissions': [('manage_products', 'Может изменять товары')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
