# Generated by Django 5.2.12 on 2026-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='price_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='quantity_gte_0',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='product_quantity_gte_0'),
        ),
    ]
