# Generated by Django 5.2.12 on 2026-03-31 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_price_gte_0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='sell_counter_gte_0',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_counter',
        ),
    ]
