# Generated by Django 5.2.12 on 2026-04-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_products_ca_slug_da4386_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/products/default.webp', null=True, upload_to='img/products/%Y/%m/%d', verbose_name='Картинка товара'),
        ),
    ]
